"""Home improvement mock adapter.

Returns hardcoded search results for each query in example_queries.csv.
Keyed by exact query string; falls back to an empty list for unknown queries.

Replace this with real API calls to your search endpoint.
"""

from veritail.types import SearchResponse, SearchResult

# ---------------------------------------------------------------------------
# Pre-populated mock catalog for a home improvement retailer
# Format: query -> list of product dicts
# ---------------------------------------------------------------------------

_CATALOG: dict[str, list[dict]] = {
    "12/2 romex wire 250 ft": [
        {
            "product_id": "SOUTHWIRE-28828255",
            "title": "Southwire 12/2 NM-B Romex Wire 250 ft Roll",
            "description": "Southwire 12/2 NM-B with ground residential electrical wire. 250 ft roll. Suitable for 20-amp circuits. UL listed. Copper conductors with PVC insulation and nylon jacket.",
            "category": "Electrical > Wire",
            "price": 139.00,
            "attributes": {
                "gauge": "12/2",
                "length": "250 ft",
                "type": "NM-B",
                "conductor": "Copper",
                "ampacity": "20A",
                "brand": "Southwire",
                "ul_listed": "Yes",
            },
            "in_stock": True,
        },
        {
            "product_id": "CERROWIRE-147-4203J",
            "title": "Cerro Wire 12/2 NM-B Wire with Ground 250 ft",
            "description": "Cerro 12/2 NM-B copper building wire for interior residential wiring. 250 ft coil. Rated for 20-amp circuits per NEC.",
            "category": "Electrical > Wire",
            "price": 134.97,
            "attributes": {
                "gauge": "12/2",
                "length": "250 ft",
                "type": "NM-B",
                "conductor": "Copper",
                "ampacity": "20A",
                "brand": "Cerro Wire",
            },
            "in_stock": True,
        },
        {
            "product_id": "SOUTHWIRE-28828201",
            "title": "Southwire 12/2 NM-B Romex Wire 50 ft Roll",
            "description": "Southwire 12/2 NM-B with ground. 50 ft roll for smaller projects. UL listed for 20-amp circuits.",
            "category": "Electrical > Wire",
            "price": 36.97,
            "attributes": {
                "gauge": "12/2",
                "length": "50 ft",
                "type": "NM-B",
                "conductor": "Copper",
                "ampacity": "20A",
                "brand": "Southwire",
            },
            "in_stock": True,
        },
        {
            "product_id": "SOUTHWIRE-28828228",
            "title": "Southwire 12/2 NM-B Romex Wire 100 ft Roll",
            "description": "Southwire 12/2 NM-B with ground residential electrical wire. 100 ft roll. UL listed.",
            "category": "Electrical > Wire",
            "price": 62.97,
            "attributes": {
                "gauge": "12/2",
                "length": "100 ft",
                "type": "NM-B",
                "conductor": "Copper",
                "ampacity": "20A",
                "brand": "Southwire",
            },
            "in_stock": True,
        },
        {
            "product_id": "SOUTHWIRE-63946872",
            "title": "Southwire 14/2 NM-B Romex Wire 250 ft Roll",
            "description": "Southwire 14/2 NM-B with ground. 250 ft roll. Suitable for 15-amp circuits only. UL listed.",
            "category": "Electrical > Wire",
            "price": 99.00,
            "attributes": {
                "gauge": "14/2",
                "length": "250 ft",
                "type": "NM-B",
                "conductor": "Copper",
                "ampacity": "15A",
                "brand": "Southwire",
            },
            "in_stock": True,
        },
    ],
    "brushed nickel cabinet pulls": [
        {
            "product_id": "FRANKLIN-P29615K-SN-B",
            "title": "Franklin Brass 5 in. Brushed Nickel Elongated Cabinet Pull (10-Pack)",
            "description": "Classic bar pull with 5 in. center-to-center. Brushed nickel finish. Includes mounting hardware. 10-pack for multi-cabinet projects.",
            "category": "Hardware > Cabinet Hardware",
            "price": 24.98,
            "attributes": {
                "finish": "Brushed Nickel",
                "length": "5 in.",
                "center_to_center": "5 in.",
                "style": "Bar Pull",
                "pack_size": "10",
                "brand": "Franklin Brass",
            },
            "in_stock": True,
        },
        {
            "product_id": "AMEROCK-BP37007G10",
            "title": "Amerock Mulholland 3 in. Brushed Nickel Cabinet Pull",
            "description": "Transitional style pull with 3 in. center-to-center spacing. Brushed nickel finish complements a range of kitchen and bath styles.",
            "category": "Hardware > Cabinet Hardware",
            "price": 5.48,
            "attributes": {
                "finish": "Brushed Nickel",
                "center_to_center": "3 in.",
                "style": "Transitional",
                "brand": "Amerock",
            },
            "in_stock": True,
        },
        {
            "product_id": "LIBERTY-P01014C-SN-C",
            "title": "Liberty Essentials 3-3/4 in. Brushed Nickel Cabinet Pull",
            "description": "Simple streamlined design. Brushed nickel finish. 3-3/4 in. center-to-center. Zinc die cast construction.",
            "category": "Hardware > Cabinet Hardware",
            "price": 3.28,
            "attributes": {
                "finish": "Brushed Nickel",
                "center_to_center": "3-3/4 in.",
                "material": "Zinc Die Cast",
                "brand": "Liberty",
            },
            "in_stock": True,
        },
        {
            "product_id": "AMEROCK-BP53005ORB",
            "title": "Amerock Allison 3 in. Oil-Rubbed Bronze Cabinet Pull",
            "description": "Classic pull in oil-rubbed bronze finish. 3 in. center-to-center. Warm traditional look.",
            "category": "Hardware > Cabinet Hardware",
            "price": 3.98,
            "attributes": {
                "finish": "Oil-Rubbed Bronze",
                "center_to_center": "3 in.",
                "style": "Traditional",
                "brand": "Amerock",
            },
            "in_stock": True,
        },
        {
            "product_id": "FRANKLIN-P29618K-SN-B",
            "title": "Franklin Brass 5 in. Brushed Nickel Cabinet Knob (10-Pack)",
            "description": "Round cabinet knob in brushed nickel. 10-pack. 1-1/4 in. diameter.",
            "category": "Hardware > Cabinet Hardware",
            "price": 19.98,
            "attributes": {
                "finish": "Brushed Nickel",
                "type": "Knob",
                "diameter": "1-1/4 in.",
                "pack_size": "10",
                "brand": "Franklin Brass",
            },
            "in_stock": True,
        },
    ],
    "pressure treated 4x4 post 8ft": [
        {
            "product_id": "PT-4X4X8-GC",
            "title": "4 in. x 4 in. x 8 ft. #2 Pressure-Treated Ground Contact Southern Pine Timber",
            "description": "Pressure treated for ground contact (UC4A). Actual dimensions 3.5 in. x 3.5 in. x 8 ft. Suitable for fence posts, deck supports, and structural applications.",
            "category": "Lumber > Treated Lumber",
            "price": 14.98,
            "attributes": {
                "nominal_size": "4x4",
                "length": "8 ft",
                "actual_size": "3.5 in. x 3.5 in.",
                "treatment": "Ground Contact (UC4A)",
                "species": "Southern Yellow Pine",
                "grade": "#2",
            },
            "in_stock": True,
        },
        {
            "product_id": "PT-4X4X8-AG",
            "title": "4 in. x 4 in. x 8 ft. #2 Pressure-Treated Above Ground Southern Pine Timber",
            "description": "Pressure treated for above ground use only (UC3B). Not rated for ground contact or direct burial. Actual dimensions 3.5 in. x 3.5 in.",
            "category": "Lumber > Treated Lumber",
            "price": 11.98,
            "attributes": {
                "nominal_size": "4x4",
                "length": "8 ft",
                "actual_size": "3.5 in. x 3.5 in.",
                "treatment": "Above Ground (UC3B)",
                "species": "Southern Yellow Pine",
                "grade": "#2",
            },
            "in_stock": True,
        },
        {
            "product_id": "PT-4X4X10-GC",
            "title": "4 in. x 4 in. x 10 ft. #2 Pressure-Treated Ground Contact Southern Pine Timber",
            "description": "Pressure treated for ground contact (UC4A). 10 ft length. Actual dimensions 3.5 in. x 3.5 in.",
            "category": "Lumber > Treated Lumber",
            "price": 19.48,
            "attributes": {
                "nominal_size": "4x4",
                "length": "10 ft",
                "actual_size": "3.5 in. x 3.5 in.",
                "treatment": "Ground Contact (UC4A)",
                "species": "Southern Yellow Pine",
            },
            "in_stock": True,
        },
        {
            "product_id": "PT-6X6X8-GC",
            "title": "6 in. x 6 in. x 8 ft. #2 Pressure-Treated Ground Contact Southern Pine Timber",
            "description": "Heavy-duty structural post. Ground contact rated (UC4A). Actual dimensions 5.5 in. x 5.5 in. x 8 ft.",
            "category": "Lumber > Treated Lumber",
            "price": 29.98,
            "attributes": {
                "nominal_size": "6x6",
                "length": "8 ft",
                "actual_size": "5.5 in. x 5.5 in.",
                "treatment": "Ground Contact (UC4A)",
                "species": "Southern Yellow Pine",
            },
            "in_stock": True,
        },
        {
            "product_id": "FENCE-POST-STEEL",
            "title": "Oz-Post T4-850 4 in. Steel Fence Post Anchor",
            "description": "Steel anchor bracket for setting 4x4 posts without concrete. Drive-in installation.",
            "category": "Building Materials > Structural Hardware",
            "price": 34.97,
            "attributes": {
                "fits_post": "4x4",
                "material": "Steel",
                "type": "Post Anchor",
                "brand": "Oz-Post",
            },
            "in_stock": True,
        },
    ],
    "matte black bathroom faucet": [
        {
            "product_id": "DELTA-B2596LF-BL",
            "title": "Delta Windemere 4 in. Centerset 2-Handle Bathroom Faucet in Matte Black",
            "description": "Two-handle centerset faucet with 4 in. center-to-center. Matte black finish. WaterSense certified. Metal pop-up drain assembly included.",
            "category": "Plumbing > Faucets",
            "price": 79.00,
            "attributes": {
                "finish": "Matte Black",
                "type": "Centerset",
                "handles": "2",
                "faucet_centers": "4 in.",
                "brand": "Delta",
                "certification": "WaterSense",
            },
            "in_stock": True,
        },
        {
            "product_id": "MOEN-84115BL",
            "title": "Moen Adler Single-Handle Bathroom Faucet in Matte Black",
            "description": "Single-handle lever faucet with matte black finish. 4 in. centerset. Includes pop-up drain. WaterSense certified at 1.2 GPM.",
            "category": "Plumbing > Faucets",
            "price": 69.00,
            "attributes": {
                "finish": "Matte Black",
                "type": "Centerset",
                "handles": "1",
                "flow_rate": "1.2 GPM",
                "brand": "Moen",
                "certification": "WaterSense",
            },
            "in_stock": True,
        },
        {
            "product_id": "PFISTER-LG142-060B",
            "title": "Pfister Pfirst Modern Single Control Bathroom Faucet in Matte Black",
            "description": "Contemporary single-handle faucet. Matte black finish. Push and seal drain. Pforever seal advanced valve technology.",
            "category": "Plumbing > Faucets",
            "price": 54.98,
            "attributes": {
                "finish": "Matte Black",
                "handles": "1",
                "brand": "Pfister",
                "certification": "WaterSense",
            },
            "in_stock": True,
        },
        {
            "product_id": "MOEN-84115SRN",
            "title": "Moen Adler Single-Handle Bathroom Faucet in Spot Resist Brushed Nickel",
            "description": "Single-handle lever faucet with Spot Resist brushed nickel finish. 4 in. centerset.",
            "category": "Plumbing > Faucets",
            "price": 79.00,
            "attributes": {
                "finish": "Spot Resist Brushed Nickel",
                "type": "Centerset",
                "handles": "1",
                "brand": "Moen",
            },
            "in_stock": True,
        },
        {
            "product_id": "DELTA-B3596LF-BL",
            "title": "Delta Windemere Widespread Bathroom Faucet in Matte Black",
            "description": "Two-handle widespread faucet with 8 in. center-to-center. Matte black finish. Separate hot and cold handles.",
            "category": "Plumbing > Faucets",
            "price": 149.00,
            "attributes": {
                "finish": "Matte Black",
                "type": "Widespread",
                "handles": "2",
                "faucet_centers": "8 in.",
                "brand": "Delta",
            },
            "in_stock": True,
        },
    ],
    "dewalt 20v drill": [
        {
            "product_id": "DEWALT-DCD771C2",
            "title": "DEWALT 20V MAX Cordless Drill/Driver Kit (DCD771C2)",
            "description": "Compact and lightweight 20V MAX lithium-ion drill/driver. 1/2 in. single-sleeve ratcheting chuck. Two-speed transmission (0-450/0-1500 RPM). Includes 2 batteries, charger, and bag.",
            "category": "Tools > Power Tools",
            "price": 99.00,
            "attributes": {
                "voltage": "20V MAX",
                "chuck_size": "1/2 in.",
                "speed": "2-Speed",
                "brand": "DEWALT",
                "batteries_included": "2",
                "type": "Drill/Driver",
            },
            "in_stock": True,
        },
        {
            "product_id": "DEWALT-DCD791D2",
            "title": "DEWALT 20V MAX XR Brushless Compact Drill/Driver Kit (DCD791D2)",
            "description": "Brushless motor for up to 57% more runtime. Compact design at 7.52 in. front to back. High-performance 2-speed transmission. Includes 2 batteries, charger, and kit bag.",
            "category": "Tools > Power Tools",
            "price": 179.00,
            "attributes": {
                "voltage": "20V MAX XR",
                "chuck_size": "1/2 in.",
                "motor": "Brushless",
                "brand": "DEWALT",
                "batteries_included": "2",
                "type": "Drill/Driver",
            },
            "in_stock": True,
        },
        {
            "product_id": "DEWALT-DCK240C2",
            "title": "DEWALT 20V MAX Drill/Driver and Impact Driver Combo Kit (DCK240C2)",
            "description": "Two-tool combo kit with drill/driver and 1/4 in. impact driver. 20V MAX system. Includes 2 batteries, charger, and contractor bag.",
            "category": "Tools > Power Tools",
            "price": 149.00,
            "attributes": {
                "voltage": "20V MAX",
                "brand": "DEWALT",
                "batteries_included": "2",
                "type": "Combo Kit",
                "includes": "Drill/Driver + Impact Driver",
            },
            "in_stock": True,
        },
        {
            "product_id": "DEWALT-DCD777C2",
            "title": "DEWALT 20V MAX Brushless Compact Drill/Driver (DCD777C2)",
            "description": "Compact brushless drill/driver. Lightweight at 2.4 lbs. Two-speed settings. Includes 2 batteries and charger.",
            "category": "Tools > Power Tools",
            "price": 119.00,
            "attributes": {
                "voltage": "20V MAX",
                "motor": "Brushless",
                "weight": "2.4 lbs",
                "brand": "DEWALT",
                "type": "Drill/Driver",
            },
            "in_stock": True,
        },
        {
            "product_id": "MILWAUKEE-2801-22CT",
            "title": "Milwaukee M18 Compact Brushless 1/2 in. Drill/Driver Kit",
            "description": "Milwaukee M18 system compact drill with brushless motor. 1800 RPM. Includes 2 batteries, charger, and case.",
            "category": "Tools > Power Tools",
            "price": 139.00,
            "attributes": {
                "voltage": "18V",
                "motor": "Brushless",
                "brand": "Milwaukee",
                "type": "Drill/Driver",
                "platform": "M18",
            },
            "in_stock": True,
        },
    ],
    "pex crimp tool": [
        {
            "product_id": "SHARKBITE-23251",
            "title": "SharkBite PEX Crimp Tool Kit with Decrimper and Gauge",
            "description": "All-in-one PEX crimping kit. Crimps 3/8 in., 1/2 in., and 3/4 in. copper crimp rings. Includes go/no-go gauge and decrimper.",
            "category": "Tools > Plumbing Tools",
            "price": 69.98,
            "attributes": {
                "sizes": "3/8, 1/2, 3/4 in.",
                "type": "Crimp",
                "includes": "Gauge, Decrimper",
                "brand": "SharkBite",
            },
            "in_stock": True,
        },
        {
            "product_id": "IWISS-F1807",
            "title": "IWISS PEX Crimp Tool for 3/8 to 1 in. Copper Crimp Rings",
            "description": "Heavy-duty PEX crimp tool with interchangeable jaws. Works with F1807 standard copper crimp rings.",
            "category": "Tools > Plumbing Tools",
            "price": 39.99,
            "attributes": {
                "sizes": "3/8 to 1 in.",
                "standard": "F1807",
                "type": "Crimp",
                "brand": "IWISS",
            },
            "in_stock": True,
        },
        {
            "product_id": "APOLLO-69PTKH0015K",
            "title": "Apollo PEX Pinch Clamp Tool with Gauge",
            "description": "Stainless steel cinch clamp tool. One-hand operation. Includes go/no-go gauge. Works with 3/8 to 1 in. stainless pinch clamps.",
            "category": "Tools > Plumbing Tools",
            "price": 44.99,
            "attributes": {
                "sizes": "3/8 to 1 in.",
                "type": "Pinch/Cinch Clamp",
                "brand": "Apollo",
            },
            "in_stock": True,
        },
        {
            "product_id": "SHARKBITE-PEX-FITTINGS-KIT",
            "title": "SharkBite 1/2 in. PEX Crimp Ring and Fitting Starter Kit",
            "description": "Starter kit with assorted 1/2 in. brass crimp fittings (elbows, tees, couplings) and copper crimp rings.",
            "category": "Plumbing > PEX Fittings",
            "price": 29.98,
            "attributes": {
                "size": "1/2 in.",
                "type": "Fitting Kit",
                "brand": "SharkBite",
            },
            "in_stock": True,
        },
        {
            "product_id": "MILWAUKEE-2473-22",
            "title": "Milwaukee M12 Force Logic Press Tool Kit",
            "description": "Battery-powered pressing tool for ProPress copper and PEX press connections. M12 platform. Includes jaws and case.",
            "category": "Tools > Plumbing Tools",
            "price": 399.00,
            "attributes": {
                "type": "Press Tool",
                "platform": "M12",
                "brand": "Milwaukee",
            },
            "in_stock": True,
        },
    ],
    "kohler toilet": [
        {
            "product_id": "KOHLER-K-3999-0",
            "title": "KOHLER Highline Two-Piece Elongated 1.28 GPF Toilet in White",
            "description": "Comfort height elongated bowl with Class Five flushing technology. 1.28 GPF for WaterSense compliance. Chair-height seating for comfort.",
            "category": "Plumbing > Toilets",
            "price": 229.00,
            "attributes": {
                "brand": "Kohler",
                "type": "Two-Piece",
                "bowl_shape": "Elongated",
                "gpf": "1.28",
                "color": "White",
                "height": "Comfort Height",
                "certification": "WaterSense",
            },
            "in_stock": True,
        },
        {
            "product_id": "KOHLER-K-3817-0",
            "title": "KOHLER Memoirs Stately Two-Piece Elongated 1.28 GPF Toilet in White",
            "description": "Classic architectural styling with AquaPiston flushing technology. Comfort height. 1.28 GPF. Includes left-hand trip lever.",
            "category": "Plumbing > Toilets",
            "price": 349.00,
            "attributes": {
                "brand": "Kohler",
                "type": "Two-Piece",
                "bowl_shape": "Elongated",
                "gpf": "1.28",
                "color": "White",
                "style": "Traditional",
            },
            "in_stock": True,
        },
        {
            "product_id": "KOHLER-K-78080-0",
            "title": "KOHLER Gleam One-Piece Elongated 1.28 GPF Skirted Toilet in White",
            "description": "Skirted one-piece design for easy cleaning. Elongated bowl. Revolution 360 flushing. WaterSense certified.",
            "category": "Plumbing > Toilets",
            "price": 469.00,
            "attributes": {
                "brand": "Kohler",
                "type": "One-Piece",
                "bowl_shape": "Elongated",
                "gpf": "1.28",
                "color": "White",
                "design": "Skirted",
            },
            "in_stock": True,
        },
        {
            "product_id": "AMERICANSTD-765AA101",
            "title": "American Standard Champion 4 Max Two-Piece Elongated 1.28 GPF Toilet in White",
            "description": "Champion 4 flushing system. Virtually clog-free. EverClean surface inhibits bacterial growth. 1.28 GPF.",
            "category": "Plumbing > Toilets",
            "price": 249.00,
            "attributes": {
                "brand": "American Standard",
                "type": "Two-Piece",
                "bowl_shape": "Elongated",
                "gpf": "1.28",
                "color": "White",
            },
            "in_stock": True,
        },
        {
            "product_id": "KOHLER-GP1083167",
            "title": "KOHLER Toilet Fill Valve Assembly",
            "description": "Replacement fill valve for Kohler toilets. Universal fit for most Kohler models.",
            "category": "Plumbing > Toilet Parts",
            "price": 14.98,
            "attributes": {
                "brand": "Kohler",
                "type": "Fill Valve",
                "compatibility": "Universal Kohler",
            },
            "in_stock": True,
        },
    ],
    "milwaukee m18 battery": [
        {
            "product_id": "MILWAUKEE-48-11-1850",
            "title": "Milwaukee M18 REDLITHIUM XC5.0 Extended Capacity Battery Pack",
            "description": "M18 5.0 Ah battery pack. REDLITHIUM intelligence provides optimized performance and overload protection. Compatible with all Milwaukee M18 tools.",
            "category": "Tools > Batteries",
            "price": 99.00,
            "attributes": {
                "platform": "M18",
                "capacity": "5.0 Ah",
                "brand": "Milwaukee",
                "type": "Battery Pack",
            },
            "in_stock": True,
        },
        {
            "product_id": "MILWAUKEE-48-11-1862",
            "title": "Milwaukee M18 REDLITHIUM HIGH OUTPUT XC6.0 Battery (2-Pack)",
            "description": "High output 6.0 Ah battery 2-pack. 50% more power and runs 50% cooler vs standard packs. M18 platform.",
            "category": "Tools > Batteries",
            "price": 199.00,
            "attributes": {
                "platform": "M18",
                "capacity": "6.0 Ah",
                "pack_size": "2",
                "brand": "Milwaukee",
                "line": "HIGH OUTPUT",
            },
            "in_stock": True,
        },
        {
            "product_id": "MILWAUKEE-48-11-1820",
            "title": "Milwaukee M18 REDLITHIUM 2.0 Compact Battery Pack",
            "description": "Compact 2.0 Ah battery for lighter weight applications. Compatible with all M18 tools.",
            "category": "Tools > Batteries",
            "price": 49.00,
            "attributes": {
                "platform": "M18",
                "capacity": "2.0 Ah",
                "brand": "Milwaukee",
                "type": "Compact Battery",
            },
            "in_stock": True,
        },
        {
            "product_id": "MILWAUKEE-48-59-1812",
            "title": "Milwaukee M18/M12 Multi-Voltage Charger",
            "description": "Charges both M12 and M18 battery packs. LED fuel gauge. Sequential charging.",
            "category": "Tools > Chargers",
            "price": 49.00,
            "attributes": {
                "platform": "M18/M12",
                "brand": "Milwaukee",
                "type": "Charger",
            },
            "in_stock": True,
        },
        {
            "product_id": "DEWALT-DCB205-2",
            "title": "DEWALT 20V MAX XR Premium Lithium-Ion 5.0 Ah Battery (2-Pack)",
            "description": "DEWALT 20V MAX battery 2-pack. 5.0 Ah capacity. Fuel gauge. Compatible with all DEWALT 20V MAX tools.",
            "category": "Tools > Batteries",
            "price": 149.00,
            "attributes": {
                "platform": "20V MAX",
                "capacity": "5.0 Ah",
                "pack_size": "2",
                "brand": "DEWALT",
            },
            "in_stock": True,
        },
    ],
    "deck screws": [
        {
            "product_id": "GRK-772691-17225",
            "title": "GRK RT Composite #8 x 2-1/2 in. Star Drive Deck Screws (500-Count)",
            "description": "Designed for composite and PVC decking. Reduced head for smooth finish. Star drive. ACQ compatible coating.",
            "category": "Fasteners > Screws",
            "price": 49.97,
            "attributes": {
                "size": "#8 x 2-1/2 in.",
                "drive": "Star (T-15)",
                "count": "500",
                "material": "Coated Steel",
                "brand": "GRK",
                "use": "Composite Decking",
            },
            "in_stock": True,
        },
        {
            "product_id": "DECKMATE-STAR-8X3",
            "title": "Deck Mate #8 x 3 in. Star Flat-Head Wood Deck Screw (1 lb. Box)",
            "description": "Tan coated deck screw for pressure-treated and cedar wood decking. Star drive. Flat head. Approx. 90 screws per lb.",
            "category": "Fasteners > Screws",
            "price": 9.98,
            "attributes": {
                "size": "#8 x 3 in.",
                "drive": "Star",
                "material": "Coated Steel",
                "brand": "Deck Mate",
                "use": "Wood Decking",
            },
            "in_stock": True,
        },
        {
            "product_id": "GRIP-RITE-MAXS3DSBK",
            "title": "Grip-Rite PrimeGuard MAX #10 x 3 in. Star Drive Deck Screw (5 lb. Bucket)",
            "description": "Premium coated deck screw for pressure-treated lumber. Meets ACQ and CA-C requirements. Star drive with Type 17 point.",
            "category": "Fasteners > Screws",
            "price": 32.97,
            "attributes": {
                "size": "#10 x 3 in.",
                "drive": "Star",
                "count": "~350",
                "material": "Coated Steel",
                "brand": "Grip-Rite",
            },
            "in_stock": True,
        },
        {
            "product_id": "CAMO-345129",
            "title": "CAMO 2-3/8 in. Edge Deck Screw Starter Kit with Marksman Pro Tool",
            "description": "Hidden deck fastener system. Drives screws into the edge of deck boards for a fastener-free surface. Includes Marksman Pro guide and 350 screws.",
            "category": "Fasteners > Deck Fasteners",
            "price": 79.98,
            "attributes": {
                "length": "2-3/8 in.",
                "type": "Edge Fastener",
                "count": "350",
                "brand": "CAMO",
            },
            "in_stock": True,
        },
        {
            "product_id": "HILLMAN-48416",
            "title": "Hillman #6 x 1-5/8 in. Phillips Drywall Screws (1 lb.)",
            "description": "Interior drywall screws for attaching drywall to wood studs. Phillips drive. Fine thread. Phosphate coated.",
            "category": "Fasteners > Screws",
            "price": 6.97,
            "attributes": {
                "size": "#6 x 1-5/8 in.",
                "drive": "Phillips",
                "use": "Drywall",
                "material": "Phosphate Coated",
                "brand": "Hillman",
            },
            "in_stock": False,
        },
    ],
    "kitchen faucet": [
        {
            "product_id": "MOEN-87233SRS",
            "title": "Moen Adler Single-Handle Pull-Down Sprayer Kitchen Faucet in Spot Resist Stainless",
            "description": "Pull-down sprayer with Reflex system for smooth retraction. Power Clean spray technology. 1 or 3 hole installation.",
            "category": "Plumbing > Faucets",
            "price": 119.00,
            "attributes": {
                "finish": "Spot Resist Stainless",
                "type": "Pull-Down",
                "handles": "1",
                "brand": "Moen",
                "installation": "1 or 3 hole",
            },
            "in_stock": True,
        },
        {
            "product_id": "DELTA-19936-SS-DST",
            "title": "Delta Leland Single-Handle Pull-Down Kitchen Faucet in Stainless",
            "description": "High-arc pull-down faucet with MagnaTite docking. Diamond Seal valve. Stainless finish.",
            "category": "Plumbing > Faucets",
            "price": 234.00,
            "attributes": {
                "finish": "Stainless",
                "type": "Pull-Down",
                "handles": "1",
                "brand": "Delta",
            },
            "in_stock": True,
        },
        {
            "product_id": "KRAUS-KPF-1610SS",
            "title": "Kraus Bolden Single-Handle Pull-Down Kitchen Faucet in Stainless Steel",
            "description": "Commercial-style dual function sprayer. Stainless steel finish. Single lever handle. All-Brite spot-free finish.",
            "category": "Plumbing > Faucets",
            "price": 179.95,
            "attributes": {
                "finish": "Stainless Steel",
                "type": "Pull-Down",
                "style": "Commercial",
                "brand": "Kraus",
            },
            "in_stock": True,
        },
        {
            "product_id": "KOHLER-K-596-VS",
            "title": "KOHLER Simplice Single-Handle Pull-Down Kitchen Faucet in Vibrant Stainless",
            "description": "3-function sprayhead with sweep spray. DockNetik magnetic docking. ProMotion technology for smooth operation.",
            "category": "Plumbing > Faucets",
            "price": 269.00,
            "attributes": {
                "finish": "Vibrant Stainless",
                "type": "Pull-Down",
                "handles": "1",
                "brand": "Kohler",
            },
            "in_stock": True,
        },
        {
            "product_id": "PFISTER-LG534-LPMSS",
            "title": "Pfister Lita Single-Handle Pull-Down Kitchen Faucet in Stainless Steel with Xtract",
            "description": "Built-in water filtration. Pull-down sprayer. Stainless steel finish. Xtract reduces chlorine and particulates.",
            "category": "Plumbing > Faucets",
            "price": 299.00,
            "attributes": {
                "finish": "Stainless Steel",
                "type": "Pull-Down",
                "brand": "Pfister",
                "feature": "Built-In Water Filtration",
            },
            "in_stock": True,
        },
    ],
    "intrior paint": [
        {
            "product_id": "BEHR-PPG-2050-1GAL",
            "title": "BEHR ULTRA Interior Paint & Primer in One - Eggshell, Ultra Pure White, 1 Gal",
            "description": "Stain-blocking paint and primer in one. Eggshell finish. Low odor. Excellent hide and coverage. Mildew resistant.",
            "category": "Paint > Interior Paint",
            "price": 38.98,
            "attributes": {
                "finish": "Eggshell",
                "color": "Ultra Pure White",
                "size": "1 Gallon",
                "brand": "BEHR",
                "line": "ULTRA",
                "coverage": "Up to 400 sq. ft./gal",
            },
            "in_stock": True,
        },
        {
            "product_id": "BEHR-DYNASTY-1GAL",
            "title": "BEHR DYNASTY Interior Paint & Primer - Matte, 1 Gal, Ultra Pure White",
            "description": "Premium one-coat hide interior paint. Scuff resistant, stain repellent. Self-priming. Low VOC.",
            "category": "Paint > Interior Paint",
            "price": 59.98,
            "attributes": {
                "finish": "Matte",
                "color": "Ultra Pure White",
                "size": "1 Gallon",
                "brand": "BEHR",
                "line": "DYNASTY",
            },
            "in_stock": True,
        },
        {
            "product_id": "PPG-TIMELESS-1GAL",
            "title": "PPG Timeless Interior Paint + Primer, Semi-Gloss, Pure White/Base 1, 1 Gal",
            "description": "Ultra premium paint and primer. One coat coverage with scuff defense. Semi-gloss finish resists stains and scuffs.",
            "category": "Paint > Interior Paint",
            "price": 55.98,
            "attributes": {
                "finish": "Semi-Gloss",
                "color": "Pure White/Base 1",
                "size": "1 Gallon",
                "brand": "PPG",
                "line": "Timeless",
            },
            "in_stock": True,
        },
        {
            "product_id": "BEHR-PREM-5GAL",
            "title": "BEHR Premium Plus Interior Flat Paint, Ultra Pure White, 5 Gal",
            "description": "Trusted quality interior flat paint. Low odor. Zero VOC. Ideal for ceilings and low-traffic walls.",
            "category": "Paint > Interior Paint",
            "price": 129.00,
            "attributes": {
                "finish": "Flat",
                "color": "Ultra Pure White",
                "size": "5 Gallon",
                "brand": "BEHR",
                "line": "Premium Plus",
            },
            "in_stock": True,
        },
        {
            "product_id": "WOOSTER-R562-9",
            "title": "Wooster Pro/Doo-Z 9 in. x 3/8 in. Nap Roller Cover",
            "description": "Woven fabric roller cover for all paints and stains. Smooth to semi-smooth finish. 3/8 in. nap for smooth walls.",
            "category": "Paint > Painting Tools",
            "price": 6.97,
            "attributes": {
                "size": "9 in.",
                "nap": "3/8 in.",
                "type": "Roller Cover",
                "brand": "Wooster",
            },
            "in_stock": True,
        },
    ],
    "ceiling fan": [
        {
            "product_id": "HUNTER-53237",
            "title": "Hunter Builder Plus 52 in. Indoor Brushed Nickel Ceiling Fan with Light Kit",
            "description": "5-blade ceiling fan with bowl light kit. 3-speed reversible motor. WhisperWind motor for quiet operation. Pull chain control.",
            "category": "Electrical > Lighting & Fans",
            "price": 89.99,
            "attributes": {
                "blade_span": "52 in.",
                "motor": "WhisperWind",
                "finish": "Brushed Nickel",
                "light": "Yes",
                "control": "Pull Chain",
                "location": "Indoor",
                "brand": "Hunter",
            },
            "in_stock": True,
        },
        {
            "product_id": "HBay-YG204-BN",
            "title": "Hampton Bay Hugger 52 in. LED Indoor Brushed Nickel Ceiling Fan with Light Kit",
            "description": "Low-profile hugger mount for 8 ft. ceilings. LED light kit included. 3-speed reversible. Pull chain. Flush mount.",
            "category": "Electrical > Lighting & Fans",
            "price": 59.97,
            "attributes": {
                "blade_span": "52 in.",
                "mount": "Flush/Hugger",
                "light": "LED",
                "finish": "Brushed Nickel",
                "location": "Indoor",
                "brand": "Hampton Bay",
            },
            "in_stock": True,
        },
        {
            "product_id": "HUNTER-59243",
            "title": "Hunter Dempsey 52 in. Indoor/Outdoor Matte Nickel Ceiling Fan with Remote",
            "description": "Modern design suitable for indoor or covered outdoor use. Includes handheld remote and LED light kit. Reversible blades.",
            "category": "Electrical > Lighting & Fans",
            "price": 229.99,
            "attributes": {
                "blade_span": "52 in.",
                "control": "Remote",
                "light": "LED",
                "finish": "Matte Nickel",
                "location": "Indoor/Outdoor Damp Rated",
                "brand": "Hunter",
            },
            "in_stock": True,
        },
        {
            "product_id": "HBay-YG528-MWH",
            "title": "Hampton Bay Mena 54 in. Indoor/Outdoor Matte White Ceiling Fan with Remote",
            "description": "Modern design with 3 blades. Integrated LED light. Wi-Fi enabled for smart home control. Damp rated.",
            "category": "Electrical > Lighting & Fans",
            "price": 149.00,
            "attributes": {
                "blade_span": "54 in.",
                "control": "Remote + Wi-Fi",
                "light": "LED",
                "finish": "Matte White",
                "location": "Indoor/Outdoor Damp Rated",
                "brand": "Hampton Bay",
            },
            "in_stock": True,
        },
        {
            "product_id": "HUNTER-51023",
            "title": "Hunter Conroy 42 in. Indoor Low Profile Antique Pewter Ceiling Fan",
            "description": "Low-profile fan ideal for small rooms and low ceilings. 42 in. blade span. 3-speed reversible. No light kit.",
            "category": "Electrical > Lighting & Fans",
            "price": 59.99,
            "attributes": {
                "blade_span": "42 in.",
                "mount": "Low Profile",
                "light": "No",
                "finish": "Antique Pewter",
                "location": "Indoor",
                "brand": "Hunter",
            },
            "in_stock": True,
        },
    ],
    "3/4 inch copper 90 degree elbow": [
        {
            "product_id": "NIBCO-W01540T",
            "title": "NIBCO 3/4 in. Copper Pressure 90-Degree Fitting Elbow",
            "description": "3/4 in. C x C copper 90-degree elbow. For sweat/solder connections. Meets ASTM B75 and B88 standards. Lead-free.",
            "category": "Plumbing > Fittings",
            "price": 2.12,
            "attributes": {
                "size": "3/4 in.",
                "angle": "90 Degree",
                "connection": "C x C (Sweat)",
                "material": "Copper",
                "brand": "NIBCO",
                "lead_free": "Yes",
            },
            "in_stock": True,
        },
        {
            "product_id": "MUELLER-W01566T",
            "title": "Mueller Streamline 3/4 in. Copper 90-Degree Elbow",
            "description": "3/4 in. copper pressure fitting. Cup x cup sweat connection. Lead-free per Safe Drinking Water Act.",
            "category": "Plumbing > Fittings",
            "price": 2.28,
            "attributes": {
                "size": "3/4 in.",
                "angle": "90 Degree",
                "connection": "C x C (Sweat)",
                "material": "Copper",
                "brand": "Mueller",
            },
            "in_stock": True,
        },
        {
            "product_id": "SHARKBITE-U256LFA",
            "title": "SharkBite 3/4 in. Push-to-Connect 90-Degree Elbow",
            "description": "No-solder push-fit 90-degree elbow. Works with copper, CPVC, and PEX. Instant connection. Removable and reusable.",
            "category": "Plumbing > Fittings",
            "price": 11.18,
            "attributes": {
                "size": "3/4 in.",
                "angle": "90 Degree",
                "connection": "Push-to-Connect",
                "compatibility": "Copper, CPVC, PEX",
                "brand": "SharkBite",
            },
            "in_stock": True,
        },
        {
            "product_id": "NIBCO-W01541T",
            "title": "NIBCO 1/2 in. Copper Pressure 90-Degree Fitting Elbow",
            "description": "1/2 in. C x C copper 90-degree elbow. For sweat/solder connections. Lead-free.",
            "category": "Plumbing > Fittings",
            "price": 1.08,
            "attributes": {
                "size": "1/2 in.",
                "angle": "90 Degree",
                "connection": "C x C (Sweat)",
                "material": "Copper",
                "brand": "NIBCO",
            },
            "in_stock": True,
        },
        {
            "product_id": "NIBCO-W01543T",
            "title": "NIBCO 3/4 in. Copper Pressure 45-Degree Fitting Elbow",
            "description": "3/4 in. C x C copper 45-degree elbow. For sweat/solder connections. Lead-free.",
            "category": "Plumbing > Fittings",
            "price": 3.08,
            "attributes": {
                "size": "3/4 in.",
                "angle": "45 Degree",
                "connection": "C x C (Sweat)",
                "material": "Copper",
                "brand": "NIBCO",
            },
            "in_stock": True,
        },
    ],
    "gfci outlet 20 amp white": [
        {
            "product_id": "LEVITON-GFNT2-W",
            "title": "Leviton 20 Amp Self-Test SmartlockPro GFCI Outlet in White",
            "description": "20A GFCI receptacle with SmartlockPro self-test technology. Automatically tests every 3 seconds. Status indicator light. UL listed.",
            "category": "Electrical > Outlets",
            "price": 19.97,
            "attributes": {
                "amperage": "20A",
                "type": "GFCI",
                "color": "White",
                "self_test": "Yes",
                "brand": "Leviton",
                "ul_listed": "Yes",
            },
            "in_stock": True,
        },
        {
            "product_id": "EATON-TRSGF20W",
            "title": "Eaton 20 Amp Self-Test GFCI Receptacle in White",
            "description": "Tamper-resistant self-test GFCI. Audible trip alert. LED status indicator. 20A rated. Meets NEC 2020 requirements.",
            "category": "Electrical > Outlets",
            "price": 17.97,
            "attributes": {
                "amperage": "20A",
                "type": "GFCI",
                "color": "White",
                "tamper_resistant": "Yes",
                "brand": "Eaton",
            },
            "in_stock": True,
        },
        {
            "product_id": "LEVITON-GFWT2-W",
            "title": "Leviton 20 Amp Weather-Resistant GFCI Outlet in White",
            "description": "20A weather-resistant GFCI for outdoor and wet locations. Self-test with lockout. SmartlockPro technology.",
            "category": "Electrical > Outlets",
            "price": 23.47,
            "attributes": {
                "amperage": "20A",
                "type": "GFCI",
                "color": "White",
                "weather_resistant": "Yes",
                "brand": "Leviton",
            },
            "in_stock": True,
        },
        {
            "product_id": "LEVITON-T5820-W",
            "title": "Leviton 20 Amp Tamper-Resistant Standard Outlet in White",
            "description": "Standard 20A duplex receptacle. Tamper-resistant shutters. Not GFCI. White. Back and side wired.",
            "category": "Electrical > Outlets",
            "price": 2.97,
            "attributes": {
                "amperage": "20A",
                "type": "Standard Duplex",
                "color": "White",
                "brand": "Leviton",
            },
            "in_stock": True,
        },
        {
            "product_id": "LEVITON-GFNT2-I",
            "title": "Leviton 20 Amp Self-Test SmartlockPro GFCI Outlet in Ivory",
            "description": "Same SmartlockPro GFCI as the white version but in ivory color. 20A rated.",
            "category": "Electrical > Outlets",
            "price": 19.97,
            "attributes": {
                "amperage": "20A",
                "type": "GFCI",
                "color": "Ivory",
                "self_test": "Yes",
                "brand": "Leviton",
            },
            "in_stock": True,
        },
    ],
    "self drilling drywall anchors": [
        {
            "product_id": "TOGGLER-SNAPTOGGLE",
            "title": "TOGGLER SnapToggle 1/4 in.-20 Heavy-Duty Toggle Bolt (10-Pack)",
            "description": "Holds up to 265 lbs in 1/2 in. drywall. Reusable. Requires 1/2 in. pilot hole. Ideal for heavy shelving and TV mounts.",
            "category": "Fasteners > Anchors",
            "price": 14.98,
            "attributes": {
                "size": "1/4-20",
                "type": "Toggle Bolt",
                "capacity": "265 lbs",
                "count": "10",
                "brand": "TOGGLER",
            },
            "in_stock": True,
        },
        {
            "product_id": "EZ-ANCOR-25200",
            "title": "E-Z Ancor Twist-N-Lock Self-Drilling Drywall Anchors, Medium Duty (50-Pack)",
            "description": "Self-drilling nylon drywall anchor. No pre-drill needed. Holds up to 75 lbs in 1/2 in. drywall. Phillips drive.",
            "category": "Fasteners > Anchors",
            "price": 9.97,
            "attributes": {
                "type": "Self-Drilling",
                "material": "Nylon",
                "capacity": "75 lbs",
                "count": "50",
                "brand": "E-Z Ancor",
            },
            "in_stock": True,
        },
        {
            "product_id": "HILLMAN-376256",
            "title": "Hillman Self-Drilling Zinc Drywall Anchor with Screws (4-Pack)",
            "description": "Zinc self-drilling anchor with #8 screws. Holds up to 50 lbs. No pre-drilling required. For hollow wall applications.",
            "category": "Fasteners > Anchors",
            "price": 3.97,
            "attributes": {
                "type": "Self-Drilling",
                "material": "Zinc",
                "capacity": "50 lbs",
                "count": "4",
                "brand": "Hillman",
            },
            "in_stock": True,
        },
        {
            "product_id": "EZ-ANCOR-25310",
            "title": "E-Z Ancor Stud Solver #7 Self-Drilling Drywall Anchor (50-Pack)",
            "description": "Self-drilling zinc anchor. Holds up to 50 lbs per anchor. #7 x 1-1/4 in. Phillips drive head. No pilot hole needed.",
            "category": "Fasteners > Anchors",
            "price": 12.97,
            "attributes": {
                "type": "Self-Drilling",
                "material": "Zinc",
                "capacity": "50 lbs",
                "count": "50",
                "brand": "E-Z Ancor",
            },
            "in_stock": True,
        },
        {
            "product_id": "3M-CLAW-25LB",
            "title": "3M CLAW Drywall Picture Hanger 25 lb. (4-Pack)",
            "description": "No tools needed. Pin-style hanger for drywall. Holds up to 25 lbs. Leaves small hole. Not a screw-in anchor.",
            "category": "Hardware > Picture Hanging",
            "price": 6.48,
            "attributes": {
                "type": "Picture Hanger",
                "capacity": "25 lbs",
                "count": "4",
                "brand": "3M",
            },
            "in_stock": True,
        },
    ],
    "led recessed light 6 inch retrofit": [
        {
            "product_id": "HALO-LT560WH6930R",
            "title": "Halo LT560 6 in. LED Retrofit Recessed Light, 3000K, White Baffle",
            "description": "65W equivalent LED retrofit trim. 3000K warm white. 850 lumens. Fits existing 6 in. recessed housings. EZ Click Clip installation. Energy Star rated.",
            "category": "Electrical > Lighting",
            "price": 9.97,
            "attributes": {
                "size": "6 in.",
                "type": "Retrofit",
                "color_temp": "3000K",
                "lumens": "850",
                "wattage": "10.6W",
                "certification": "Energy Star",
                "brand": "Halo",
            },
            "in_stock": True,
        },
        {
            "product_id": "COMMERCIAL-ELEC-T61CL",
            "title": "Commercial Electric 6 in. Selectable CCT LED Recessed Retrofit Trim",
            "description": "5 selectable color temperatures (2700K-5000K). 900 lumens. Fits standard 6 in. housings. Dimmable. IC and non-IC rated.",
            "category": "Electrical > Lighting",
            "price": 7.97,
            "attributes": {
                "size": "6 in.",
                "type": "Retrofit",
                "color_temp": "2700K-5000K Selectable",
                "lumens": "900",
                "dimmable": "Yes",
                "brand": "Commercial Electric",
            },
            "in_stock": True,
        },
        {
            "product_id": "HALO-RL56099S1EWH",
            "title": "Halo RL56 6 in. LED Retrofit Recessed Light, Selectable CCT, White",
            "description": "Selectable CCT (2700K, 3000K, 3500K, 4000K, 5000K). 900 lumens. Dimmable. Title 24/JA8 compliant.",
            "category": "Electrical > Lighting",
            "price": 11.97,
            "attributes": {
                "size": "6 in.",
                "type": "Retrofit",
                "color_temp": "Selectable CCT",
                "lumens": "900",
                "dimmable": "Yes",
                "brand": "Halo",
            },
            "in_stock": True,
        },
        {
            "product_id": "COMMERCIAL-ELEC-T612CL-4PK",
            "title": "Commercial Electric 6 in. Selectable CCT LED Retrofit Trim (4-Pack)",
            "description": "Value 4-pack of 6 in. retrofit trims. 5 selectable color temperatures. 900 lumens each. Dimmable.",
            "category": "Electrical > Lighting",
            "price": 27.97,
            "attributes": {
                "size": "6 in.",
                "type": "Retrofit",
                "color_temp": "Selectable CCT",
                "pack_size": "4",
                "brand": "Commercial Electric",
            },
            "in_stock": True,
        },
        {
            "product_id": "HALO-HLA406FL9FS1EMWR",
            "title": "Halo 4 in. LED Canless Recessed Light, Selectable CCT",
            "description": "4 in. canless LED downlight. No housing needed. Selectable CCT. Suitable for new construction and remodel.",
            "category": "Electrical > Lighting",
            "price": 12.97,
            "attributes": {
                "size": "4 in.",
                "type": "Canless",
                "color_temp": "Selectable CCT",
                "brand": "Halo",
            },
            "in_stock": True,
        },
    ],
    "bathroom exhaust fan with light": [
        {
            "product_id": "BROAN-AE80BL",
            "title": "Broan-NuTone 80 CFM Ceiling Bathroom Exhaust Fan with LED Light",
            "description": "80 CFM ventilation fan with integrated LED light. 1.5 sone. Energy Star rated. Fits 2x6 construction. 4 in. duct.",
            "category": "Electrical > Ventilation",
            "price": 69.00,
            "attributes": {
                "cfm": "80",
                "sone": "1.5",
                "light": "LED",
                "duct_size": "4 in.",
                "brand": "Broan-NuTone",
                "certification": "Energy Star",
            },
            "in_stock": True,
        },
        {
            "product_id": "BROAN-AE110LK",
            "title": "Broan-NuTone 110 CFM Ceiling Bathroom Exhaust Fan with LED Light and Night Light",
            "description": "110 CFM fan with LED light and amber LED night light. 1.0 sone. Energy Star. For up to 105 sq. ft. rooms.",
            "category": "Electrical > Ventilation",
            "price": 109.00,
            "attributes": {
                "cfm": "110",
                "sone": "1.0",
                "light": "LED + Night Light",
                "brand": "Broan-NuTone",
                "certification": "Energy Star",
            },
            "in_stock": True,
        },
        {
            "product_id": "DELTA-RAD80LED",
            "title": "Delta BreezRadiance 80 CFM Bathroom Exhaust Fan with LED Light and Heater",
            "description": "80 CFM fan with integrated LED light and 1300W heater. 1.5 sone. Energy Star.",
            "category": "Electrical > Ventilation",
            "price": 199.00,
            "attributes": {
                "cfm": "80",
                "sone": "1.5",
                "light": "LED",
                "heater": "1300W",
                "brand": "Delta Breez",
            },
            "in_stock": True,
        },
        {
            "product_id": "PANASONIC-FV0511VQL1",
            "title": "Panasonic WhisperCeiling DC 50/80/110 CFM Bathroom Fan with LED",
            "description": "Multi-speed fan with Pick-A-Flow selector (50/80/110 CFM). Ultra quiet 0.3 sone at 50 CFM. Built-in LED light. Energy Star.",
            "category": "Electrical > Ventilation",
            "price": 189.00,
            "attributes": {
                "cfm": "50/80/110",
                "sone": "0.3-0.9",
                "light": "LED",
                "brand": "Panasonic",
                "line": "WhisperCeiling DC",
            },
            "in_stock": True,
        },
        {
            "product_id": "BROAN-688",
            "title": "Broan-NuTone 50 CFM Ceiling/Wall Bathroom Exhaust Fan",
            "description": "Basic 50 CFM exhaust fan. No light. 4.0 sone. Ceiling or wall mount. Economy model.",
            "category": "Electrical > Ventilation",
            "price": 22.98,
            "attributes": {
                "cfm": "50",
                "sone": "4.0",
                "light": "No",
                "brand": "Broan-NuTone",
            },
            "in_stock": True,
        },
    ],
    "r-13 fiberglass insulation": [
        {
            "product_id": "OWENSCORNING-R13-KF",
            "title": "Owens Corning R-13 Kraft Faced Fiberglass Insulation Batt 23 in. x 93 in. (10-Pack)",
            "description": "R-13 unfaced kraft paper faced batt insulation. Fits 2x4 wall cavities at 23 in. on-center. 10 pieces per pack covering 150.12 sq. ft.",
            "category": "Building Materials > Insulation",
            "price": 49.98,
            "attributes": {
                "r_value": "R-13",
                "width": "23 in.",
                "length": "93 in.",
                "facing": "Kraft",
                "coverage": "150.12 sq. ft.",
                "brand": "Owens Corning",
            },
            "in_stock": True,
        },
        {
            "product_id": "OWENSCORNING-R13-UF",
            "title": "Owens Corning R-13 Unfaced Fiberglass Insulation Batt 15 in. x 93 in. (12-Pack)",
            "description": "R-13 unfaced batt insulation. Fits 2x4 wall cavities at 15 in. on-center framing. 12 pieces per pack.",
            "category": "Building Materials > Insulation",
            "price": 39.98,
            "attributes": {
                "r_value": "R-13",
                "width": "15 in.",
                "length": "93 in.",
                "facing": "Unfaced",
                "brand": "Owens Corning",
            },
            "in_stock": True,
        },
        {
            "product_id": "JOHNS-R13-KF",
            "title": "Johns Manville R-13 Kraft Faced Fiberglass Batt 15 in. x 93 in.",
            "description": "Kraft-faced R-13 batt for standard 2x4 framing. Vapor retarder facing. Formaldehyde-free.",
            "category": "Building Materials > Insulation",
            "price": 42.98,
            "attributes": {
                "r_value": "R-13",
                "width": "15 in.",
                "length": "93 in.",
                "facing": "Kraft",
                "brand": "Johns Manville",
            },
            "in_stock": True,
        },
        {
            "product_id": "OWENSCORNING-R19-KF",
            "title": "Owens Corning R-19 Kraft Faced Fiberglass Insulation Batt 15 in. x 93 in.",
            "description": "R-19 kraft faced batt for 2x6 wall and floor cavities. Higher thermal resistance than R-13.",
            "category": "Building Materials > Insulation",
            "price": 59.98,
            "attributes": {
                "r_value": "R-19",
                "width": "15 in.",
                "length": "93 in.",
                "facing": "Kraft",
                "brand": "Owens Corning",
            },
            "in_stock": True,
        },
        {
            "product_id": "OWENSCORNING-FOAMBOARD-R5",
            "title": "Owens Corning FOAMULAR 150 1 in. x 4 ft. x 8 ft. XPS Rigid Foam Board (R-5)",
            "description": "Extruded polystyrene (XPS) rigid foam board. R-5 per inch. Moisture resistant. For foundation, wall sheathing, and below-grade.",
            "category": "Building Materials > Insulation",
            "price": 36.48,
            "attributes": {
                "r_value": "R-5",
                "type": "XPS Rigid Foam",
                "thickness": "1 in.",
                "brand": "Owens Corning",
            },
            "in_stock": True,
        },
    ],
    "pvc cement blue medium body": [
        {
            "product_id": "OATEY-30891",
            "title": "Oatey Rain-R-Shine 8 oz. PVC Cement Blue Medium Body",
            "description": "Medium body blue PVC cement for wet conditions. Sets in approximately 15 minutes. For PVC pipe and fittings up to 6 in. diameter. NSF listed.",
            "category": "Plumbing > Adhesives",
            "price": 8.98,
            "attributes": {
                "size": "8 oz.",
                "type": "PVC Cement",
                "body": "Medium",
                "color": "Blue",
                "brand": "Oatey",
                "line": "Rain-R-Shine",
                "wet_application": "Yes",
            },
            "in_stock": True,
        },
        {
            "product_id": "OATEY-30893",
            "title": "Oatey Rain-R-Shine 16 oz. PVC Cement Blue Medium Body",
            "description": "Medium body blue PVC cement. Wet or dry application. 16 oz. can. For PVC pipe up to 6 in.",
            "category": "Plumbing > Adhesives",
            "price": 13.98,
            "attributes": {
                "size": "16 oz.",
                "type": "PVC Cement",
                "body": "Medium",
                "color": "Blue",
                "brand": "Oatey",
                "line": "Rain-R-Shine",
            },
            "in_stock": True,
        },
        {
            "product_id": "OATEY-30812",
            "title": "Oatey 8 oz. CPVC Cement Orange Medium Body",
            "description": "Medium body orange cement specifically for CPVC pipe and fittings. Not for PVC. For hot and cold water lines.",
            "category": "Plumbing > Adhesives",
            "price": 10.48,
            "attributes": {
                "size": "8 oz.",
                "type": "CPVC Cement",
                "body": "Medium",
                "color": "Orange",
                "brand": "Oatey",
            },
            "in_stock": True,
        },
        {
            "product_id": "OATEY-30246",
            "title": "Oatey 8 oz. Purple PVC Primer",
            "description": "Purple PVC primer required before applying PVC cement. Softens pipe surface for strong solvent welds. NSF listed.",
            "category": "Plumbing > Adhesives",
            "price": 5.78,
            "attributes": {
                "size": "8 oz.",
                "type": "PVC Primer",
                "color": "Purple",
                "brand": "Oatey",
            },
            "in_stock": True,
        },
        {
            "product_id": "OATEY-30818",
            "title": "Oatey 4 oz. PVC All-Purpose Cement Clear Regular Body",
            "description": "Clear regular-body PVC cement. For PVC pipe and fittings up to 4 in. diameter. Not for CPVC.",
            "category": "Plumbing > Adhesives",
            "price": 5.48,
            "attributes": {
                "size": "4 oz.",
                "type": "PVC Cement",
                "body": "Regular",
                "color": "Clear",
                "brand": "Oatey",
            },
            "in_stock": True,
        },
    ],
    "simpson strong tie joist hanger 2x10": [
        {
            "product_id": "SIMPSON-LUS210",
            "title": "Simpson Strong-Tie LUS210 2x10 Double-Shear Face-Mount Joist Hanger",
            "description": "Designed for 2x10 joists. Double-shear nailing for code-required connections. ZMAX galvanized coating for ACQ treated lumber. Load rated per IRC/IBC.",
            "category": "Building Materials > Structural Hardware",
            "price": 3.76,
            "attributes": {
                "fits": "2x10",
                "type": "Face Mount Joist Hanger",
                "coating": "ZMAX Galvanized",
                "brand": "Simpson Strong-Tie",
                "model": "LUS210",
            },
            "in_stock": True,
        },
        {
            "product_id": "SIMPSON-LUS210-2",
            "title": "Simpson Strong-Tie LUS210-2 Double 2x10 Joist Hanger",
            "description": "For double 2x10 lumber. ZMAX coating. Meets or exceeds code requirements. Face mount installation.",
            "category": "Building Materials > Structural Hardware",
            "price": 8.27,
            "attributes": {
                "fits": "Double 2x10",
                "type": "Face Mount Joist Hanger",
                "coating": "ZMAX Galvanized",
                "brand": "Simpson Strong-Tie",
            },
            "in_stock": True,
        },
        {
            "product_id": "SIMPSON-LUS28",
            "title": "Simpson Strong-Tie LUS28 2x8 Joist Hanger",
            "description": "Face-mount joist hanger for 2x8 lumber. ZMAX galvanized. Double-shear nailing.",
            "category": "Building Materials > Structural Hardware",
            "price": 3.18,
            "attributes": {
                "fits": "2x8",
                "type": "Face Mount Joist Hanger",
                "coating": "ZMAX Galvanized",
                "brand": "Simpson Strong-Tie",
            },
            "in_stock": True,
        },
        {
            "product_id": "SIMPSON-H10A",
            "title": "Simpson Strong-Tie H10A Hurricane Tie",
            "description": "Connects roof rafters/trusses to wall top plates. 18-gauge galvanized steel. Wind and seismic resistance.",
            "category": "Building Materials > Structural Hardware",
            "price": 1.18,
            "attributes": {
                "type": "Hurricane Tie",
                "gauge": "18",
                "brand": "Simpson Strong-Tie",
                "model": "H10A",
            },
            "in_stock": True,
        },
        {
            "product_id": "SIMPSON-SD-10X2-5-R100",
            "title": "Simpson Strong-Tie SD Connector Screw #10 x 2-1/2 in. (100-Pack)",
            "description": "Structural connector screw for Simpson Strong-Tie connectors. Replaces 10d and 16d nails per load tables.",
            "category": "Fasteners > Structural Screws",
            "price": 24.47,
            "attributes": {
                "size": "#10 x 2-1/2 in.",
                "count": "100",
                "type": "Structural Connector Screw",
                "brand": "Simpson Strong-Tie",
            },
            "in_stock": True,
        },
    ],
    "tile saw": [
        {
            "product_id": "RIDGID-R4021",
            "title": "RIDGID 7 in. Tabletop Wet Tile Saw",
            "description": "Compact 7 in. wet tile saw. 6.5 amp motor. Cuts tile up to 20 in. diagonally. Stainless steel table. Includes 7 in. diamond blade.",
            "category": "Tools > Power Tools",
            "price": 189.00,
            "attributes": {
                "blade_size": "7 in.",
                "type": "Wet Tile Saw",
                "motor": "6.5 Amp",
                "brand": "RIDGID",
            },
            "in_stock": True,
        },
        {
            "product_id": "RYOBI-WS722",
            "title": "RYOBI 7 in. 4.8 Amp Tabletop Tile Saw",
            "description": "Entry-level wet tile saw for DIY projects. 4.8 amp motor. Cuts porcelain and ceramic tile. Includes miter gauge and blade.",
            "category": "Tools > Power Tools",
            "price": 89.00,
            "attributes": {
                "blade_size": "7 in.",
                "type": "Wet Tile Saw",
                "motor": "4.8 Amp",
                "brand": "RYOBI",
            },
            "in_stock": True,
        },
        {
            "product_id": "DEWALT-D24000",
            "title": "DEWALT 10 in. Wet Tile Saw with Stand",
            "description": "Professional 10 in. wet tile saw. 1.5 HP motor. Cuts 24 in. tiles. Plunge cut capability. Stainless steel rail system. Includes stand.",
            "category": "Tools > Power Tools",
            "price": 699.00,
            "attributes": {
                "blade_size": "10 in.",
                "type": "Wet Tile Saw",
                "motor": "1.5 HP",
                "brand": "DEWALT",
            },
            "in_stock": True,
        },
        {
            "product_id": "QEP-22650Q",
            "title": "QEP 3/5 HP Wet Tile Saw with 7 in. Blade",
            "description": "Compact wet tile saw for ceramic and porcelain. 7 in. diamond blade included. Water tray for dust-free cutting.",
            "category": "Tools > Power Tools",
            "price": 64.97,
            "attributes": {
                "blade_size": "7 in.",
                "type": "Wet Tile Saw",
                "motor": "3/5 HP",
                "brand": "QEP",
            },
            "in_stock": True,
        },
        {
            "product_id": "RIDGID-R4030S",
            "title": "RIDGID 7 in. Wet Tile Saw Blade, Diamond Continuous Rim",
            "description": "Replacement 7 in. continuous rim diamond blade for wet tile saws. For ceramic and porcelain tile.",
            "category": "Tools > Saw Blades",
            "price": 9.97,
            "attributes": {
                "blade_size": "7 in.",
                "type": "Diamond Blade",
                "brand": "RIDGID",
                "use": "Ceramic/Porcelain Tile",
            },
            "in_stock": True,
        },
    ],
    "vinyl plank flooring": [
        {
            "product_id": "LIFEPROOF-I966106L",
            "title": "LifeProof Sterling Oak 8.7 in. x 47.6 in. Luxury Vinyl Plank Flooring (20.06 sq. ft./case)",
            "description": "Waterproof luxury vinyl plank with attached pad. Drop-and-lock installation. Scratch-resistant. Suitable for all rooms including bathrooms.",
            "category": "Flooring > Vinyl",
            "price": 52.67,
            "attributes": {
                "width": "8.7 in.",
                "length": "47.6 in.",
                "thickness": "7.1 mm",
                "wear_layer": "20 mil",
                "coverage": "20.06 sq. ft./case",
                "brand": "LifeProof",
                "finish": "Sterling Oak",
            },
            "in_stock": True,
        },
        {
            "product_id": "TRAFFICMASTER-82115",
            "title": "TrafficMaster Lakeshore Pecan 7.1 in. x 47.6 in. Luxury Vinyl Plank (18.73 sq. ft./case)",
            "description": "Peel and stick luxury vinyl plank. No underlayment needed. Waterproof. Easy DIY installation. 2mm thick.",
            "category": "Flooring > Vinyl",
            "price": 24.98,
            "attributes": {
                "width": "7.1 in.",
                "length": "47.6 in.",
                "thickness": "2 mm",
                "installation": "Peel and Stick",
                "coverage": "18.73 sq. ft./case",
                "brand": "TrafficMaster",
            },
            "in_stock": True,
        },
        {
            "product_id": "LIFEPROOF-I1148118L",
            "title": "LifeProof Trail Oak 8.7 in. x 47.6 in. Luxury Vinyl Plank Flooring (20.06 sq. ft./case)",
            "description": "Rigid core luxury vinyl plank. 100% waterproof. Built-in underlayment. Commercial-grade 20 mil wear layer.",
            "category": "Flooring > Vinyl",
            "price": 52.67,
            "attributes": {
                "width": "8.7 in.",
                "length": "47.6 in.",
                "thickness": "7.1 mm",
                "wear_layer": "20 mil",
                "coverage": "20.06 sq. ft./case",
                "brand": "LifeProof",
                "finish": "Trail Oak",
            },
            "in_stock": True,
        },
        {
            "product_id": "MSI-VTGSMOOAK7X48",
            "title": "MSI Woodland Mystic Oak 7 in. x 48 in. Luxury Vinyl Plank (23.77 sq. ft./case)",
            "description": "Rigid core vinyl plank. Click-lock installation. 12 mil wear layer. Suitable for residential use.",
            "category": "Flooring > Vinyl",
            "price": 42.49,
            "attributes": {
                "width": "7 in.",
                "length": "48 in.",
                "thickness": "5.5 mm",
                "wear_layer": "12 mil",
                "coverage": "23.77 sq. ft./case",
                "brand": "MSI",
            },
            "in_stock": True,
        },
        {
            "product_id": "LIFEPROOF-LVP-UNDERLAYMENT",
            "title": "LifeProof 3 ft. x 33.33 ft. Premium Vinyl Floor Underlayment (100 sq. ft. Roll)",
            "description": "Underlayment for click-lock vinyl flooring. Sound dampening. Moisture barrier. 1.5mm thick.",
            "category": "Flooring > Underlayment",
            "price": 29.98,
            "attributes": {
                "type": "Underlayment",
                "coverage": "100 sq. ft.",
                "thickness": "1.5 mm",
                "brand": "LifeProof",
            },
            "in_stock": True,
        },
    ],
    "cordless circular saw": [
        {
            "product_id": "DEWALT-DCS565B",
            "title": "DEWALT 20V MAX 6-1/2 in. Brushless Cordless Circular Saw (Tool Only)",
            "description": "Brushless motor. 6-1/2 in. blade. 5150 RPM. 2-1/8 in. depth of cut at 90 degrees. Left blade design for cut-line visibility. Tool only.",
            "category": "Tools > Power Tools",
            "price": 139.00,
            "attributes": {
                "voltage": "20V MAX",
                "blade_size": "6-1/2 in.",
                "motor": "Brushless",
                "brand": "DEWALT",
                "includes_battery": "No",
            },
            "in_stock": True,
        },
        {
            "product_id": "MILWAUKEE-2631-20",
            "title": "Milwaukee M18 7-1/4 in. Brushless Cordless Circular Saw (Tool Only)",
            "description": "M18 FUEL 7-1/4 in. circular saw. Brushless POWERSTATE motor. 5800 RPM. Magnesium shoe. Tool only.",
            "category": "Tools > Power Tools",
            "price": 199.00,
            "attributes": {
                "voltage": "M18 (18V)",
                "blade_size": "7-1/4 in.",
                "motor": "Brushless",
                "brand": "Milwaukee",
                "line": "FUEL",
            },
            "in_stock": True,
        },
        {
            "product_id": "MAKITA-XSH03Z",
            "title": "Makita 18V LXT 6-1/2 in. Brushless Cordless Circular Saw (Tool Only)",
            "description": "18V LXT brushless 6-1/2 in. circular saw. Automatic speed change technology. 5000 RPM. BL motor.",
            "category": "Tools > Power Tools",
            "price": 139.00,
            "attributes": {
                "voltage": "18V LXT",
                "blade_size": "6-1/2 in.",
                "motor": "Brushless",
                "brand": "Makita",
            },
            "in_stock": True,
        },
        {
            "product_id": "RYOBI-PCL500B",
            "title": "RYOBI ONE+ 18V 5-1/2 in. Cordless Circular Saw (Tool Only)",
            "description": "Budget-friendly cordless circular saw. 5-1/2 in. blade. 4700 RPM. 1-5/8 in. depth of cut. ONE+ battery platform.",
            "category": "Tools > Power Tools",
            "price": 49.97,
            "attributes": {
                "voltage": "18V ONE+",
                "blade_size": "5-1/2 in.",
                "brand": "RYOBI",
            },
            "in_stock": True,
        },
        {
            "product_id": "DEWALT-DWE575SB",
            "title": "DEWALT 15 Amp 7-1/4 in. Corded Lightweight Circular Saw with Electric Brake",
            "description": "Corded 15-amp circular saw. 7-1/4 in. blade. 5200 RPM. Electric brake. Lightweight 8.8 lbs.",
            "category": "Tools > Power Tools",
            "price": 109.00,
            "attributes": {
                "power": "15 Amp (Corded)",
                "blade_size": "7-1/4 in.",
                "brand": "DEWALT",
                "type": "Corded",
            },
            "in_stock": True,
        },
    ],
    "outdoor deck stain": [
        {
            "product_id": "BEHR-ST533001",
            "title": "BEHR Premium Semi-Transparent Weatherproofing Deck Stain, Cedar Naturaltone, 1 Gal",
            "description": "Semi-transparent deck stain with all-weather protection. Resists UV, rain, and mildew. For wood decks, fences, and siding. One coat coverage.",
            "category": "Paint > Exterior Stain",
            "price": 42.98,
            "attributes": {
                "finish": "Semi-Transparent",
                "color": "Cedar Naturaltone",
                "size": "1 Gallon",
                "brand": "BEHR",
                "surface": "Wood Deck/Fence",
            },
            "in_stock": True,
        },
        {
            "product_id": "CABOT-140.0019200.007",
            "title": "Cabot Australian Timber Oil Exterior Deck Stain, Honey Teak, 1 Gal",
            "description": "Oil-based translucent deck stain. Deep penetrating formula for hardwoods. UV protection. For exterior wood surfaces.",
            "category": "Paint > Exterior Stain",
            "price": 44.98,
            "attributes": {
                "finish": "Translucent Oil",
                "color": "Honey Teak",
                "size": "1 Gallon",
                "brand": "Cabot",
                "surface": "Hardwood Deck",
            },
            "in_stock": True,
        },
        {
            "product_id": "TWP-1500-1GAL",
            "title": "TWP 1500 Series Exterior Wood Preservative Stain, Cedartone, 1 Gal",
            "description": "High-performance oil-based wood preservative stain. Excellent UV protection. For decks, fences, log homes. Zero film build.",
            "category": "Paint > Exterior Stain",
            "price": 52.99,
            "attributes": {
                "finish": "Penetrating Oil",
                "color": "Cedartone",
                "size": "1 Gallon",
                "brand": "TWP",
            },
            "in_stock": True,
        },
        {
            "product_id": "BEHR-ST501001",
            "title": "BEHR Premium Solid Color Weatherproofing Deck Stain, Deep Base, 1 Gal",
            "description": "Solid color deck stain. Hides wood grain completely. Maximum UV protection. 100% acrylic formula.",
            "category": "Paint > Exterior Stain",
            "price": 42.98,
            "attributes": {
                "finish": "Solid",
                "size": "1 Gallon",
                "brand": "BEHR",
                "surface": "Wood Deck/Fence",
            },
            "in_stock": True,
        },
        {
            "product_id": "BEHR-DECK-CLEANER",
            "title": "BEHR Premium 1 Gal. All-In-One Wood Cleaner",
            "description": "Deck cleaning concentrate. Removes dirt, mildew, and weathered stain. Prepares wood for re-staining.",
            "category": "Paint > Surface Prep",
            "price": 16.98,
            "attributes": {"size": "1 Gallon", "type": "Wood Cleaner", "brand": "BEHR"},
            "in_stock": True,
        },
    ],
    "1/2 inch pex tubing 100ft red": [
        {
            "product_id": "SHARKBITE-U860R100",
            "title": "SharkBite 1/2 in. x 100 ft. Red PEX-B Tubing",
            "description": "1/2 in. PEX-B tubing. 100 ft. coil. Red for hot water lines. NSF certified. Meets ASTM F876/F877 standards. Compatible with crimp, clamp, and push-to-connect fittings.",
            "category": "Plumbing > PEX Tubing",
            "price": 39.98,
            "attributes": {
                "size": "1/2 in.",
                "length": "100 ft",
                "color": "Red",
                "type": "PEX-B",
                "brand": "SharkBite",
                "nsf_certified": "Yes",
            },
            "in_stock": True,
        },
        {
            "product_id": "APOLLO-APPR10012",
            "title": "Apollo 1/2 in. x 100 ft. Red PEX-B Pipe",
            "description": "PEX-B tubing for hot water supply. 100 ft coil. Compatible with crimp and pinch clamp fittings. NSF 14/61 listed.",
            "category": "Plumbing > PEX Tubing",
            "price": 29.98,
            "attributes": {
                "size": "1/2 in.",
                "length": "100 ft",
                "color": "Red",
                "type": "PEX-B",
                "brand": "Apollo",
            },
            "in_stock": True,
        },
        {
            "product_id": "SHARKBITE-U860B100",
            "title": "SharkBite 1/2 in. x 100 ft. Blue PEX-B Tubing",
            "description": "1/2 in. PEX-B tubing. 100 ft. coil. Blue for cold water lines. Same specifications as red.",
            "category": "Plumbing > PEX Tubing",
            "price": 39.98,
            "attributes": {
                "size": "1/2 in.",
                "length": "100 ft",
                "color": "Blue",
                "type": "PEX-B",
                "brand": "SharkBite",
            },
            "in_stock": True,
        },
        {
            "product_id": "UPONOR-F1040500",
            "title": "Uponor 1/2 in. x 100 ft. Red PEX-A Tubing (AquaPEX)",
            "description": "PEX-A tubing with expansion memory. 100 ft coil. For use with Uponor ProPEX expansion fittings only. Not compatible with crimp fittings.",
            "category": "Plumbing > PEX Tubing",
            "price": 59.98,
            "attributes": {
                "size": "1/2 in.",
                "length": "100 ft",
                "color": "Red",
                "type": "PEX-A",
                "brand": "Uponor",
                "fitting_system": "ProPEX Expansion",
            },
            "in_stock": True,
        },
        {
            "product_id": "SHARKBITE-U870R300",
            "title": "SharkBite 1/2 in. x 300 ft. Red PEX-B Tubing",
            "description": "Contractor-size 300 ft coil. 1/2 in. PEX-B. Red for hot water. For whole-house plumbing runs.",
            "category": "Plumbing > PEX Tubing",
            "price": 89.98,
            "attributes": {
                "size": "1/2 in.",
                "length": "300 ft",
                "color": "Red",
                "type": "PEX-B",
                "brand": "SharkBite",
            },
            "in_stock": True,
        },
    ],
}


# -- Search (veritail calls this function) ------------------------------------


def search(query: str) -> SearchResponse:
    """Return mock search results for the given query.

    Replace this with a real API call to your search endpoint:

        import requests
        response = requests.get(
            "https://your-api.com/search",
            params={"q": query},
            headers={"Authorization": "Bearer <token>"},
            timeout=5,
        )
        data = response.json()
        results = [
            SearchResult(
                product_id=item["sku"],
                title=item["name"],
                description=item["description"],
                category=item["category"],
                price=item["price"],
                position=i,
                attributes=item.get("attributes", {}),
                in_stock=item.get("in_stock", True),
            )
            for i, item in enumerate(data["results"])
        ]
        corrected_query = data.get("corrected_query")
        return SearchResponse(results=results, corrected_query=corrected_query)
    """
    # Simulate autocorrect: map misspelled queries to corrected versions
    corrections = {
        "intrior paint": "interior paint",
    }
    corrected_query = corrections.get(query)

    products = _CATALOG.get(query, [])

    results = [
        SearchResult(
            product_id=p["product_id"],
            title=p["title"],
            description=p["description"],
            category=p["category"],
            price=p["price"],
            position=i,
            attributes=p.get("attributes", {}),
            in_stock=p.get("in_stock", True),
            metadata=p.get("metadata", {}),
        )
        for i, p in enumerate(products)
    ]

    return SearchResponse(results=results, corrected_query=corrected_query)


# ---------------------------------------------------------------------------
# Autocomplete / type-ahead suggestions
# ---------------------------------------------------------------------------

from veritail import AutocompleteResponse  # noqa: E402

_SUGGESTIONS: dict[str, list[str]] = {
    "dr": [
        "drill",
        "drain snake",
        "drywall screws",
        "drop cloth",
        "drawer slides",
        "dryer vent kit",
    ],
    "pe": [
        "pex tubing",
        "pendant light",
        "peel and stick tile",
        "pergo flooring",
        "pegboard hooks",
        "pex crimp rings",
    ],
    "fa": [
        "faucet",
        "fan ceiling",
        "fasteners",
        "farmhouse sink",
        "fascia board",
        "fan bathroom exhaust",
    ],
    "dec": [
        "deck screws",
        "deck stain",
        "deck boards composite",
        "deck railing",
        "decorative shelf brackets",
        "deck post cap",
    ],
    "pex": [
        "pex tubing 1/2 inch",
        "pex tubing 3/4 inch",
        "pex crimp tool",
        "pex fittings",
        "pex crimp rings",
        "pex manifold",
    ],
    "gfci": [
        "gfci outlet",
        "gfci outlet 20 amp",
        "gfci breaker",
        "gfci outlet outdoor",
        "gfci outlet white",
        "gfci outlet with usb",
    ],
    "drill": [
        "drill bit set",
        "drill press",
        "drill cordless",
        "drill dewalt 20v",
        "drill bits for concrete",
        "drill impact driver combo",
    ],
    "cedar": [
        "cedar fence pickets",
        "cedar boards",
        "cedar deck boards",
        "cedar shingles",
        "cedar 4x4 post",
        "cedar fence panels",
    ],
    "romex": [
        "romex 12/2 wire",
        "romex 14/2 wire",
        "romex 10/3 wire",
        "romex wire staples",
        "romex connector",
        "romex 12/2 250 ft",
    ],
    "insula": [
        "insulation fiberglass",
        "insulation foam board",
        "insulation r-13",
        "insulation r-19",
        "insulation spray foam",
        "insulation pipe wrap",
    ],
    "dewalt": [
        "dewalt 20v drill",
        "dewalt impact driver",
        "dewalt circular saw",
        "dewalt battery 20v",
        "dewalt miter saw",
        "dewalt oscillating tool",
    ],
    "toilet": [
        "toilet",
        "toilet elongated",
        "toilet seat",
        "toilet flange",
        "toilet wax ring",
        "toilet fill valve",
    ],
    "pressure treated": [
        "pressure treated 2x4",
        "pressure treated 4x4 post",
        "pressure treated deck boards",
        "pressure treated 2x6",
        "pressure treated plywood",
        "pressure treated lattice",
    ],
    "brushed nickel cabinet": [
        "brushed nickel cabinet pulls",
        "brushed nickel cabinet knobs",
        "brushed nickel cabinet handles",
        "brushed nickel cabinet hinges",
        "brushed nickel cabinet bar pulls",
    ],
    "led recessed light 6 inch": [
        "led recessed light 6 inch retrofit",
        "led recessed light 6 inch dimmable",
        "led recessed light 6 inch 3000k",
        "led recessed light 6 inch 4000k",
        "led recessed light 6 inch canless",
    ],
    "milwaukee m18 impact driver": [
        "milwaukee m18 impact driver",
        "milwaukee m18 impact driver kit",
        "milwaukee m18 impact driver brushless",
        "milwaukee m18 impact driver fuel",
    ],
    "kohler toilet elongated": [
        "kohler toilet elongated",
        "kohler toilet elongated white",
        "kohler toilet elongated comfort height",
        "kohler toilet elongated one piece",
        "kohler toilet elongated highline",
    ],
    "self drilling drywall anchor": [
        "self drilling drywall anchors",
        "self drilling drywall anchor #8",
        "self drilling drywall anchor zinc",
        "self drilling drywall anchor with screws",
    ],
}


# -- Suggest (veritail calls this function) -----------------------------------


def suggest(prefix: str) -> AutocompleteResponse:
    """Return autocomplete suggestions for a given prefix.

    Replace this with a real API call to your autocomplete endpoint:

        response = requests.get(
            "https://your-api.com/suggest",
            params={"q": prefix},
        )
        return AutocompleteResponse(suggestions=response.json()["suggestions"])
    """
    suggestions = _SUGGESTIONS.get(prefix, [])
    return AutocompleteResponse(suggestions=suggestions)
